let
    Fonte = Csv.Document(File.Contents("C:\Users\Usuario\Documents\Marcelo\Cursos\DataScienceAcademy\Clientes.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID_Cliente", type text}, {"Idade", type text}, {"Peso", Int64.Type}, {"Altura", Int64.Type}, {"Estado Civil", type text}, {"Estado", type text}, {"Limite de Credito", Int64.Type}, {"Valor Desconto", Int64.Type}, {"Valor Compra", Int64.Type}, {"Tipo de Cliente", type text}}),

    // Substituindo valor
    #"Valor Substituido" = Table.ReplaceValue(#"Tipo Alterado", "?", "45", Replacer.ReplaceText,{"Idade"}),

    // Ajustando o tipo da variável
    #"Tipo Ajustado" = Table.TransformColumnTypes(#"Valor Substituido", {"Idade", Int64.Type}),
   // Removendo Coluna 
    #"Coluna Removida" = Table.RemoveColumns(#"Tipo Ajustado", {"Estado Civil"}),

    // Adicionando Coluna
    #"Coluna Adicionada" = Table.AddColumn(#"Coluna Removida", "Valor Final", each [Valor Compra] - [Valor Desconto]),

    // Dividindo Coluna
    #"Dividir Coluna" = Table.SplitColumn(#"Coluna Adicionada", "ID_Cliente", Splitter.SplitTextByPositions({0, 4}, false), {"ID_Cliente.1", "ID_Cliente.2"}),
    #"Coluna Dividida" = Table.TransformColumnTypes(#"Dividir Coluna", {{"ID_Cliente.1", type text}, {"ID_Cliente.2", Int64.Type}}),

    // Renomear Coluna
    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Dividida", {{"ID_Cliente.1", "Codigo"}, {"ID_Cliente.2", "ID"}}),

    // Coluna Condicional
    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Colunas Renomeadas", "% Desconto Especial", each if [Tipo de Cliente] = "Bronze" then 5 else if [Tipo de Cliente] = "Prata" then 10 else if [Tipo de Cliente] = "Ouro" then 15 else if [Tipo de Cliente] = "Diamante" then 20 else 0),

    // ajustando escala dos dados com transformação logarítmica
    #"Logaritmo de Base10 Calculado" = Table.TransformColumns(#"Coluna Condicional Adicionada", {{"Limite de Credito", Number.Log10, type number}}),
    #"Valor Substituído" = Table.ReplaceValue(#"Logaritmo de Base10 Calculado",#nan,4,Replacer.ReplaceValue,{"Limite de Credito"}),
    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",-4,49,Replacer.ReplaceValue,{"Valor Desconto"}),
    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1",-2,49,Replacer.ReplaceValue,{"Valor Desconto"}),
    #"Linhas Classificadas" = Table.Sort(#"Valor Substituído2",{{"Valor Compra", Order.Ascending}}),
    #"Linhas Superiores Removidas" = Table.Skip(#"Linhas Classificadas",9)
in
    #"Linhas Superiores Removidas"